name: Autograding Tests
'on':
  - push
  - repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
      - name: Setup java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Checkout code
        uses: actions/checkout@v4

      - name: LibraryManagementSystemTest
        id: library-management-system-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: LibraryManagementSystemTest Test
          setup-command: ''
          command: mvn test -Dtest=LibraryManagementSystemTest
          timeout: 10
          max-score: 20

      - name: ShoppingListTest
        id: shopping-list-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: ShoppingListTest Test
          setup-command: ''
          command: mvn test -Dtest=ShoppingListTest
          timeout: 10
          max-score: 20
      - name: StudentCourseRegistrationTest
        id: student-course-registration-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: StudentCourseRegistrationTest Test
          setup-command: ''
          command: mvn test -Dtest=StudentCourseRegistrationTest
          timeout: 10
          max-score: 20

      - name: StudentGradesTrackerTest
        id: student-grades-tracker-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: StudentGradesTrackerTest Test
          setup-command: ''
          command: mvn test -Dtest=StudentGradesTrackerTest
          timeout: 10
          max-score: 20

      - name: UniqueVisitorsTest
        id: unique-visitors-test
        uses: classroom-resources/autograding-command-grader@v1
        with:
          test-name: UniqueVisitorsTest Test
          setup-command: ''
          command: mvn test -Dtest=UniqueVisitorsTest
          timeout: 10
          max-score: 20

      - name: Autograding Reporter
        uses: classroom-resources/autograding-grading-reporter@v1
        env:
          LIBRARY-MANAGEMENT-SYSTEM-TEST_RESULTS: "${{ steps.library-management-system-test.outputs.result }}"
          SHOPPING-LIST-TEST_RESULTS: "${{ steps.shopping-list-test.outputs.result }}"
          STUDENT-COURSE-REGISTRATION-TEST_RESULTS: "${{ steps.student-course-registration-test.outputs.result }}"
          STUDENT-GRADES-TRACKER-TEST_RESULTS: "${{ steps.student-grades-tracker-test.outputs.result }}"
          UNIQUE-VISITORS-TEST_RESULTS: "${{ steps.unique-visitors-test.outputs.result }}"
        with:
          runners: library-management-system-test,shopping-list-test,student-course-registration-test,student-grades-tracker-test,unique-visitors-test

